filippoints/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('fp_app.urls', namespace='filip_points')),
    path('manager/', include('manager.urls', namespace='manager')),
    path('api/v1.0/', include('fp_api.urls', namespace='fp_api')),
    path('api-auth/', include('rest_framework.urls')),
]

fp_api/urls.py
from . import views
from django.conf.urls import url, include
from rest_framework import routers
from fp_app import models
from django.urls import path


# router = routers.DefaultRouter()
# router.register(r'people', views.PeopleView)

app_name = 'fp_api'

urlpatterns = [
    path('', views.api_root),
    path('people/', views.PeopleView.as_view(), name = 'people_list'),
    path('people/<int:count>/', views.PeopleView.as_view(), name = 'people_list'),
    path('points/', views.PointsView.as_view(), name = 'points'),
    path('points/<int:count>/', views.PointsView.as_view(), name = 'points'),
    path('add-person/', views.PersonInsertView.as_view(), name = 'add_person'),
    path('add-points/', views.AddPointsView.as_view(), name = 'add_points'),
    path('update-person/', views.UpdatePerson.as_view(), name = 'update_person'),
    path('update-person/<int:pk>', views.UpdatePerson.as_view(), name = 'update_person'),
     # url(r'^', include(router.urls)),
]

fp_app/urls.py
from django.urls import path
from fp_app import views

app_name = 'filip_points'

urlpatterns =[
    path('', views.Index.as_view(), name = 'index'),
    path('all/', views.PersonList.as_view(), name = 'all'),
    path('details/<int:pk>/', views.PersonDetail.as_view(), name = "details"),

]

manager/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from manager import views

app_name = 'manager'

urlpatterns =[

    path('login/', auth_views.LoginView.as_view(template_name='manager/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('new/', views.PersonCreate.as_view(), name = 'new'),
    path('edit/<int:pk>/', views.PersonEdit.as_view(), name = "edit"),
    path('add-points/<int:pk>/', views.AddPoints.as_view(), name = "add_points"),
    path('delete/<int:pk>/',views.DeletePerson.as_view(), name='delete'),
    path('remove-points/<int:pk>/',views.RemovePoints.as_view(), name = 'remove_points'),

]

fp_app/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse

class Person(models.Model):
    first_name = models.CharField(max_length = 256)
    last_name = models.CharField(max_length = 256, blank = True)
    points = models.IntegerField(default = 0)
    last_update = models.DateTimeField(default = datetime.now)

    def get_absolute_url(self):
        return reverse('filip_points:details',kwargs = {'pk':self.pk})

    def __str__(self):
        return "{0} {1}".format(self.first_name, self.last_name)


class AddedPoints(models.Model):
    person = models.ForeignKey('Person', on_delete=models.CASCADE, related_name='points_history')
    description = models.TextField()
    awarded_points = models.IntegerField()
    date = models.DateTimeField(default = datetime.now)
    class Meta():
        ordering = ['-date']

    def __str__(self):
        return "{} - {} - {} points".format(self.person, self.date.strftime("%y-%m-%d %H:%M"), self.awarded_points)

manager/forms.py
from django import forms
from fp_app.models import Person, AddedPoints

manager/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView,
                                    DetailView,CreateView,
                                    UpdateView, DeleteView)
from django.http import HttpResponse, HttpResponseRedirect
from braces.views import SelectRelatedMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from datetime import datetime

from fp_app import models
from . import forms

class PersonCreate(LoginRequiredMixin,CreateView):
    model = models.Person
    fields = ('first_name', 'last_name')
    template_name = 'manager/new_person.html'

class PersonEdit(LoginRequiredMixin,UpdateView):
    model = models.Person
    fields = ('first_name', 'last_name')
    template_name = 'manager/edit_person.html'

class DeletePerson(LoginRequiredMixin, DeleteView):
    model = models.Person
    success_url = reverse_lazy('filip_points:all')
    template_name = 'manager/person_confirm_delete.html'

class RemovePoints(LoginRequiredMixin, DeleteView):
    model = models.AddedPoints
    template_name = 'manager/remove_points.html'

    def get_success_url(self):
        person = self.object.person
        return reverse_lazy( 'filip_points:details', kwargs={'pk': person.pk})

    def delete(self, *args, **kwargs):
        object = self.get_object()
        person =object.person
        person.points -= object.awarded_points
        person.save()
        return super().delete(*args, **kwargs)

class AddPoints(LoginRequiredMixin,TemplateView):
    def get(self,request, **kwargs):
        pk = self.kwargs['pk']
        person = get_object_or_404(models.Person,pk=pk)
        return render(request, 'manager/add_points.html', context = {'person': person, })

    def post(self,request, **kwargs):

        points = int(request.POST['awarded_points'])
        description = request.POST['description']
        person_id = int(request.POST.get('person_id'))
        person = get_object_or_404(models.Person,pk = person_id)
        ap = models.AddedPoints(person = person, description = description, awarded_points = points)
        ap.save()
        person.points += points
        person.last_update = datetime.now()
        person.save()
        return redirect(reverse_lazy('filip_points:details', kwargs = {'pk': person_id}))

manager/templates/manager/add_points.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}

<div class="container my-container my-margined">
<h1 class="margined-title text-center"> Add Points To {{ person }}</h1>



<form class="my-form"  method="post">
    {% csrf_token %}

   <div class="form-group">
     <label class="control-label" for="id_description">Description</label>
     <textarea name="description" cols="40" rows="10" class="form-control" placeholder="Description" title="" required id="id_description"></textarea>
   </div>
  <div class="form-group">
  <label class="control-label" for="id_awarded_points">Awarded points</label>
  <input type="number" name="awarded_points" class="form-control" placeholder="Awarded points" title="" required id="id_awarded_points" />
  </div>


    <input type="hidden" name="person_id" value="{{person.pk}}">
    <input type="submit" name="" value="Add" class="btn btn-success small-screen-btn">
</form>
</div>

{% endblock content %}

manager/templates/manager/edit_person.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="container my-container my-margined">
    <h1 class="margined-title text-center">EditPerson</h1>

    <form class="my-form"  method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary small-screen-btn" name="" value="Edit">
    </form>
  </div>
{% endblock %}

manager/templates/manager/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
        <div class="container my-container my-margined">
          <div class="row">
              <div class="col-lg-12 ">
                <h2 class="login-title text-center">Log In</h2>
                  <h3 class="login-title text-center">For Filip only!</h3>
                <form class="my-form" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" name="" value="Login" class="btn btn-default small-screen-btn">
                </form>
              </div>
          </div>

        </div>
{% endblock content %}

manager/templates/manager/new_person.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}

  <div class="container my-container my-margined">


    <h1 class="margined-title text-center">Add New Person</h1>

    <form class="my-form" action="{% url 'manager:new' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary small-screen-btn" name="" value="Add">
    </form>
      </div>
{% endblock %}

manager/templates/manager/person_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<div class="container my-container my-margined">
  <h3 class="login-title">Are you sure you want to delete {{object}}?</h3>


  <form class="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large small-screen-btn">
  	<a href="{% url 'filip_points:details' pk=object.pk %}" class="btn btn-simple btn-large btn-default small-screen-btn">Cancel</a>

  </form>

</div>
{% endblock content %}

manager/templates/manager/remove_points.html
{% extends "base.html" %}

{% block content %}
<div class="container my-container my-margined">
  <h3 class="login-title">Are you sure you want to remove this? </h3>

  <dl class="dl-horizontal">
      <dt>Person</dt>
      <dd>
          {{object.person}}
      </dd>
      <dt>Points</dt>
      <dd>{{object.awarded_points}}</dd>
      <dt>
          Description
      </dt>
      <dd>
      {{object.description}}</dd>
  </dl>

  <form class="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Removal" class="btn btn-danger btn-large small-screen-btn">
  	<a href="{% url 'filip_points:details' pk=object.person.pk %}" class="btn btn-simple btn-large btn-default small-screen-btn">Cancel</a>

  </form>
</div>
{% endblock content %}