filippoints/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('fp_app.urls', namespace='filip_points')),
    path('manager/', include('manager.urls', namespace='manager')),
    path('api/v1.0/', include('fp_api.urls', namespace='fp_api')),
    path('api-auth/', include('rest_framework.urls')),
]

fp_api/urls.py
from . import views
from django.conf.urls import url, include
from rest_framework import routers
from fp_app import models
from django.urls import path


# router = routers.DefaultRouter()
# router.register(r'people', views.PeopleView)

app_name = 'fp_api'

urlpatterns = [
    path('', views.api_root),
    path('people/', views.PeopleView.as_view(), name = 'people_list'),
    path('people/<int:count>/', views.PeopleView.as_view(), name = 'people_list'),
    path('points/', views.PointsView.as_view(), name = 'points'),
    path('points/<int:count>/', views.PointsView.as_view(), name = 'points'),
    path('add-person/', views.PersonInsertView.as_view(), name = 'add_person'),
    path('add-points/', views.AddPointsView.as_view(), name = 'add_points'),
    path('update-person/', views.UpdatePerson.as_view(), name = 'update_person'),
    path('update-person/<int:pk>', views.UpdatePerson.as_view(), name = 'update_person'),
     # url(r'^', include(router.urls)),
]

fp_app/urls.py
from django.urls import path
from fp_app import views

app_name = 'filip_points'

urlpatterns =[
    path('', views.Index.as_view(), name = 'index'),
    path('all/', views.PersonList.as_view(), name = 'all'),
    path('details/<int:pk>/', views.PersonDetail.as_view(), name = "details"),

]

manager/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from manager import views

app_name = 'manager'

urlpatterns =[

    path('login/', auth_views.LoginView.as_view(template_name='manager/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('new/', views.PersonCreate.as_view(), name = 'new'),
    path('edit/<int:pk>/', views.PersonEdit.as_view(), name = "edit"),
    path('add-points/<int:pk>/', views.AddPoints.as_view(), name = "add_points"),
    path('delete/<int:pk>/',views.DeletePerson.as_view(), name='delete'),
    path('remove-points/<int:pk>/',views.RemovePoints.as_view(), name = 'remove_points'),

]

fp_app/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse

class Person(models.Model):
    first_name = models.CharField(max_length = 256)
    last_name = models.CharField(max_length = 256, blank = True)
    points = models.IntegerField(default = 0)
    last_update = models.DateTimeField(default = datetime.now)

    def get_absolute_url(self):
        return reverse('filip_points:details',kwargs = {'pk':self.pk})

    def __str__(self):
        return "{0} {1}".format(self.first_name, self.last_name)


class AddedPoints(models.Model):
    person = models.ForeignKey('Person', on_delete=models.CASCADE, related_name='points_history')
    description = models.TextField()
    awarded_points = models.IntegerField()
    date = models.DateTimeField(default = datetime.now)
    class Meta():
        ordering = ['-date']

    def __str__(self):
        return "{} - {} - {} points".format(self.person, self.date.strftime("%y-%m-%d %H:%M"), self.awarded_points)

fp_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView,CreateView
from django.http import HttpResponse, HttpResponseRedirect
from braces.views import SelectRelatedMixin, PrefetchRelatedMixin

from . import models



class Index(ListView):
    model = models.Person
    ordering = ['-points']
    template_name = 'fp_app/index.html'

class PersonList(ListView):
    model = models.Person
    ordering = ['-points']


class PersonDetail(DetailView):
    model = models.Person

fp_app/templates/fp_app/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}


<!-- Intro Section -->
	<div class="hero-section">
		<div class="hero-content">
			<div class="hero-center">
			<!-- 	<img src="img/big-logo.png" alt=""> -->
{#				<p class="slider-text">Get the FilipPoints!</p>#}
			</div>
		</div>
		<!-- slider -->
		<div id="hero-slider" class="owl-carousel">

			<div class="item  hero-item" data-bg="{% static 'images/filip.jpg' %}"></div>
      <div class="item  hero-item" data-bg="{% static 'images/filip2.jpg' %}"></div>
        <div class="item  hero-item" data-bg="{% static 'images/filip3.jpg' %}"></div>
		</div>
	</div>
	<!-- Intro Section -->


	<!-- About section -->
	<div class="about-section">
		<div class="overlay"></div>
		<!-- card section -->
		<div class="card-section">
			<div class="container">
				<div class="row">
					<!-- single card -->
					<div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
						<div class="lab-card">
							<div class="icon">
								<i class="flaticon-018-laptop-1"></i>
							</div>
							<h2>Earn Your FilipPoints!</h2>
							<p> when hanging out with <br><b>Filip!</b></p>
						</div>
					</div>
					<!-- single card -->
					<div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
						<div class="lab-card">
							<div class="icon">
								<i class="flaticon-011-compass"></i>
							</div>
							<h2>Check your FilipPoints!</h2>
                            <p> on www.filippoints.com also on your smartphone!</p>
						</div>
					</div>
					<!-- single card -->
					<div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
						<div class="lab-card">
							<div class="icon">
								<i class="flaticon-012-cube"></i>
							</div>
							<h2>Exchange your FilipPoints!</h2>
							<p>for coffee with Filip or a T-shirt with his picture! Cheers!</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- card section end-->


		<!-- About contant -->
		<div class="about-contant my-container">
			<div class="container-fluid">
				<div class="section-title">
					<h2><span>Top 10</span> People with points</h2>
				</div>
				<div class="row">
          <table class="table table-bordered table-responsive index-table">
            <thead>
              <tr>
								<th>#</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Points</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for person in person_list|slice:"10" %}
                <tr>
									<td>{{forloop.counter}}</td>
                  <td>{{person.first_name}}</td>
                  <td>{{person.last_name}}</td>
                  <td>{{person.points}}</td>
                  <td class="text-center">
                      <a class="btn btn-primary" href="{% url 'filip_points:details' pk=person.pk %}">Details</a>
                  </td>
                </tr>
              {% endfor %}

            </tbody>
          </table>
				</div>


			</div>
		</div>
	</div>
	<!-- About section end -->




{% endblock content %}

fp_app/templates/fp_app/person_detail.html
{% extends "base.html" %}



{% block content %}

<!-- Page header -->
	<div class="page-top-section">
		<div class="overlay"></div>
		<div class="container text-right">
			<div class="page-info">
				<h2>Person Details</h2>
				<div class="page-links">
					<a href="/">Home</a>
					<span>Details</span>
				</div>
			</div>
		</div>
	</div>
	<!-- Page header end-->


	<!-- page section -->
	<div class="page-section spad">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-sm-7 blog-posts">
					<!-- Single Post -->
					<div class="single-post">

						<div class="post-content">
							<h2 class="post-title">{{object}}</h2>
							<div class="post-meta">
								<a>{{object.points}} Points</a>
								<a>last update: {{object.last_update|date:'Y-m-d H:i'}}</a>

							</div>
							<div class="site-accordions">

                  {% if object.points_history.all %}
									<div class="panel-group" id="accordion">
										<!-- Single Accordions -->

                      {% for item in object.points_history.all %}
										<div class="panel">
											<div class="panel-heading">
												<h4 class="panel-title">  {{item.date|date:'Y-m-d H:i'}} - {{item.awarded_points}} points</h4>
												<a data-toggle="collapse" data-parent="#accordion" href="#accordion{{item.pk}}" class="collapsed" aria-expanded="false"></a>
											</div>
											<div id="accordion{{item.pk}}" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
												<div class="panel-body">
													<p>
                              {{item.description}}
                          </p>
                          {% if user.is_authenticated %}
                              	<p>
                                    <a href="{% url 'manager:remove_points' pk=item.pk %}" class="btn btn-danger rmv-btn small-screen-btn">Remove</a>
                                </p>
                          {% endif %}


												</div>
											</div>
										</div>

                    {% endfor %}

									</div>

                  {% endif %}
								</div>
						</div>


					</div>
				</div>
				<!-- Sidebar area -->
				<div class="col-md-4 col-sm-5 sidebar">
				  {% if user.is_authenticated %}
					<!-- Single widget -->
					<div class="widget-item">
						<h2 class="widget-title">Actions</h2>
						<ul class="tag">
              <li><a href="{% url 'manager:add_points' pk=object.pk %}">Add Points</a></li>
							<li class="my-danger"><a href="{% url 'manager:delete' pk=object.pk %}" class="my-danger">Delete Person</a></li>
							<li class="my-warning"><a href="{% url 'manager:edit' pk=object.pk %}" class="my-warning">Edit Person</a></li>

						</ul>
					</div>
		  {% endif %}
				</div>
			</div>
		</div>
	</div>
	<!-- page section end-->


{% endblock content %}

fp_app/templates/fp_app/person_list.html
{% extends "base.html" %}

{% block content %}
<!-- Page header -->
	<div class="page-top-section">
		<div class="overlay"></div>
		<div class="container text-right">
			<div class="page-info">
				<h2>All People</h2>
				<div class="page-links">
					<a href="/">Home</a>
					<span>All</span>
				</div>
			</div>
		</div>
	</div>
	<!-- Page header end-->



  <!-- About contant -->
  <div class="about-contant my-container with-bg">

    <div class="container-fluid">

      <div class="row">
        <table class="table table-bordered table-responsive index-table">
          <thead>
            <tr>
							<th>#</th>
              <th>Name</th>
              <th>Surname</th>
              <th>Points</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for person in person_list %}
              <tr>
								<td>{{forloop.counter}}</td>
                <td>{{person.first_name}}</td>
                <td>{{person.last_name}}</td>
                <td>{{person.points}}</td>
                <td class="text-center">
                    <a class="btn btn-primary" href="{% url 'filip_points:details' pk=person.pk %}">Details</a>
                </td>
              </tr>
            {% endfor %}

          </tbody>
        </table>
      </div>


    </div>
  </div>
</div>




{% endblock content %}