filippoints/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('fp_app.urls', namespace='filip_points')),
    path('manager/', include('manager.urls', namespace='manager')),
    path('api/v1.0/', include('fp_api.urls', namespace='fp_api')),
    path('api-auth/', include('rest_framework.urls')),
]

fp_api/urls.py
from . import views
from django.conf.urls import url, include
from rest_framework import routers
from fp_app import models
from django.urls import path


# router = routers.DefaultRouter()
# router.register(r'people', views.PeopleView)

app_name = 'fp_api'

urlpatterns = [
    path('', views.api_root),
    path('people/', views.PeopleView.as_view(), name = 'people_list'),
    path('people/<int:count>/', views.PeopleView.as_view(), name = 'people_list'),
    path('points/', views.PointsView.as_view(), name = 'points'),
    path('points/<int:count>/', views.PointsView.as_view(), name = 'points'),
    path('add-person/', views.PersonInsertView.as_view(), name = 'add_person'),
    path('add-points/', views.AddPointsView.as_view(), name = 'add_points'),
    path('update-person/', views.UpdatePerson.as_view(), name = 'update_person'),
    path('update-person/<int:pk>', views.UpdatePerson.as_view(), name = 'update_person'),
     # url(r'^', include(router.urls)),
]

fp_app/urls.py
from django.urls import path
from fp_app import views

app_name = 'filip_points'

urlpatterns =[
    path('', views.Index.as_view(), name = 'index'),
    path('all/', views.PersonList.as_view(), name = 'all'),
    path('details/<int:pk>/', views.PersonDetail.as_view(), name = "details"),

]

manager/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from manager import views

app_name = 'manager'

urlpatterns =[

    path('login/', auth_views.LoginView.as_view(template_name='manager/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('new/', views.PersonCreate.as_view(), name = 'new'),
    path('edit/<int:pk>/', views.PersonEdit.as_view(), name = "edit"),
    path('add-points/<int:pk>/', views.AddPoints.as_view(), name = "add_points"),
    path('delete/<int:pk>/',views.DeletePerson.as_view(), name='delete'),
    path('remove-points/<int:pk>/',views.RemovePoints.as_view(), name = 'remove_points'),

]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>FilipPoints</title>
    <!-- Favicon -->
    	<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon"/>

    	<!-- Google Fonts -->
    	<link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500,700|Roboto:300,400,700" rel="stylesheet">

    	<!-- Stylesheets -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
    	<link rel="stylesheet" href="{% static 'css/flaticon.css' %}"/>
    	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
    	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}"/>
    	 <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body class="">
    <!-- Page Preloder -->
    <div id="preloder">
      <div class="loader">
        <img src="" alt="">
        <h2>Loading.....</h2>
      </div>
    </div>
    <!-- Header section -->
        <header class="header-section">
          <div class="logo">
              <a href="/"><img src="{% static 'images/logo.png' %}" alt=""></a>
            <!-- Logo -->
          </div>
          <!-- Navigation -->
          <div class="responsive"><i class="fa fa-bars"></i></div>
          <nav>
            <ul class="menu-list">
              <li class="active"><a href="{% url 'filip_points:index' %}">Home</a></li>
              <li><a href="{% url 'filip_points:all' %}">All People</a></li>
              {% if user.is_authenticated %}
                   <li><a href="{% url 'manager:new' %}">New Person</a></li>


                    <li><a href="{% url 'manager:logout' %}">Log out</a></li>
              {% else %}

                    <li><a href="{% url 'manager:login' %}">Log in</a></li>

              {% endif %}
            </ul>
          </nav>
        </header>
        <!-- Header section end -->


            {% block content %}

            {% endblock %}




     	<!-- Footer section -->
     	<!-- <footer class="footer-section">
     		<h2>2017 All rights reserved. Designed by <a href="https://colorlib.com" target="_blank">Colorlib</a></h2>
     	</footer> -->
     	<!-- Footer section end -->


      <!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/circle-progress.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

  </body>

</html>